var verkstad = [{
    "name":"Cykeltoppen",
    "latitude":59.850525,
    "longitude":17.591515,
    "description":"",
    "timeOpen":
    {
        "monday":"09-19",
        "tuesday":"09-19",
        "wednesday":"09-19",
        "thursday":"09-19",
        "friday":"09-19",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"018461090",
    "address":"Sernanders väg 8\n752 61, Uppsala",
    "website":"",
    "email":""
},{
    "name":"Leffes Cykel",
    "latitude":59.860436,
    "longitude":17.612371,
    "description":"Vi säljer och servar nya och begagnade cyklar. I vår verkstad kan vi erbjuda alla typer av reparationer på din cykel, då vi har kunnig personal som uppdaterar och utbildar sig på det nya som kommer på marknaden.\n\nLeffes Cykel grundades 1986 av Leif Ahlström som varit i cykelbranchen sedan 1963 (blott 13 år gammal började han jobba på Hickes). Men drömmen om eget blev verklig i mars 1986 då Gunnar ''Gurra'' Svensson skulle gå i pension. Idag har vi utökat butiken och verkstaden och är med Leffe fyra som jobbar tillsammans.",
    "timeOpen":
    {
        "monday":"08-18",
        "tuesday":"08-18",
        "wednesday":"08-18",
        "thursday":"08-18",
        "friday":"08-18",
        "saturday":"10-14",
        "sunday":""
    },
    "phoneNumber":"018536045",
    "address":"Sibyllegatan 9 \n752 31, Uppsala",
    "website":"https://www.facebook.com/pages/Leffes-Cykel/132732710132272",
    "email":"leffescykel@live.se"
},{
    "name":"Cykel-Viktor",
    "latitude":59.861560,
    "longitude":17.634007,
    "description":"I vår cykelverkstad fixar vi alla fel som kan uppstå på din cykel. Allt från punktering till helrenovering till bra pris. Lämna in din cykel trasig och få tillbaka den hel dagen efter är vår målsättning, många gånger går det snabbare tack vare riktigt duktig och professionell personal i verkstaden.\n\nHär monteras och justeras även alla nya cyklar innan de levereras från butiken och börjar rulla på gator och vägar.",
    "timeOpen":
    {
        "monday":"08-17",
        "tuesday":"08-17",
        "wednesday":"08-17",
        "thursday":"08-17",
        "friday":"08-17",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"018138740",
    "address":"Svartbäcksgatan 25 \n753 32, Uppsala",
    "website":"http://c-s.se",
    "email":"cykel@c-s.se"
},{
    "name":"Cykelringen",
    "latitude":59.846022,
    "longitude":17.665544,
    "description":"Cykelringen har idag 11 cykelaffärer i Sverige, varav sju i Stockholm, en i Uppsala, en i Västerås, en i Örebro och en i Göteborg. Våra cykelbutiker håller öppet alla dagar under året utom nyårsdagen.\n\nFöretaget grundades 1980 och är idag en av landets största återförsäljare av cyklar och fitnessprodukter.\n\nVi säljer ett brett sortiment av herrcyklar, damcyklar och barncyklar. Hos oss hittar du alla modeller - BMX, mountainbikes, citybikes, cruisers, trekkingbikes och mycket mer.\n\nFörutom cyklar säljer Cykelringen en rad andra produkter för sport och fritid så som cykelhjälmar, cykelvagnar, trehjulingar, enhjulingar och sparkcyklar. Vi har också ett komplett utbud av fitnessprodukter såsom motionscyklar och andra träningsprodukter. Vintertid hittar du även längdskidor, skridskor och vinterleksaker i våra butiker.\n\nSjälvklart har vi också alla vanligt förekommande reservdelar för cyklar. I våra butiker finns dessutom cykelverkstad, där vi kan reparera de flesta cyklar som finns på marknaden.\n\nGenom rationell distribution och stora inköpsvolymer kan vi erbjuda ett mycket prisvärt sortiment.",
    "timeOpen":
    {
        "monday":"10-20",
        "tuesday":"10-20",
        "wednesday":"10-20",
        "thursday":"10-20",
        "friday":"10-20",
        "saturday":"10-18",
        "sunday":"10-18"
    },
    "phoneNumber":"018696180",
    "address":"Kungsgatan 115 \n753 18, Uppsala",
    "website":"http://www.cykelringen.se",
    "email":"info@cykelringen.se"
},
    {
        "name":"ABBA Cykelcenter",
        "latitude":59.861324,
        "longitude":17.640266,
        "description":"ABBA Cykelcenter är en cykelaffär i centrala Uppsala som säljer både nya och begagnade cyklar. Här hittar du även reservdelar såväl nya som äldre cyklar. I cykelverkstaden kan du få hjälp med reparationer samt skridskoslipning.\n\nABBA Cykelcenter startades i augusti 2004 av mig, Hesam Rashed. \n\nJag började redan som barn att jobba i min farbrors cykelverkstad. Jag riktar mig i första hand till privatpersoner, men också stora som små företag som behöver cykelservice.",
        "timeOpen":
        {
            "monday":"10-18",
            "tuesday":"10-18",
            "wednesday":"10-18",
            "thursday":"10-18",
            "friday":"10-17",
            "saturday":"",
            "sunday":""
        },
        "phoneNumber":"07701950950",
        "address":"S:t Persgatan 18A\n753 20, Uppsala",
        "website":"http://www.abbacykelcenter.com/",
        "email":"abbacykelcenter@hotmail.com"
    },
    {
        "name":"TB Cykel och Verkstad",
        "latitude":59.87467,
        "longitude":17.619452,
        "description":"TB Cykel och Verkstad är fortsättningen på lång och gedigen tradition av cykelreparationer och försäljning som påbörjades 1949 på denna adress i undersköna Tunabackar.\n\nI TB:s cykel och verkstad är målsättningen att reparera allt på hjul! Här sker också försäljning av cyklar, både nya och begagnade, samt reservdelar och tillbehör till både nya och gamla cyklar.",
        "timeOpen":
        {
            "monday":"9-18 (Stängt 13-14)",
            "tuesday":"9-18 (Stängt 13-14)",
            "wednesday":"9-18 (Stängt 13-14)",
            "thursday":"9-18 (Stängt 13-14)",
            "friday":"9-17 (Stängt 13-14)",
            "saturday":"",
            "sunday":""
        },
        "phoneNumber":"0184708669",
        "address":"Folkungagatan 21 A\n753 36, Uppsala",
        "website":"",
        "email":"tbcykel@gmail.com"
    },{
        "name":"Stahléns Cykel",
        "latitude":59.864556,
        "longitude":17.651768,
        "description":"Jag har under åren samlat på mig en hel del reservdelar till äldre cyklar. Mitt mål är att kunna reparera din cykel samma dag du lämnar in den. Jag reparerar cyklar, säljer begagnade cyklar och reservdelar (även till äldre, ''omöjlig'' cyklar).\n\nJag slipar även skridskor och långfärdsskridskor.\n\nTitta gärna in på min hemsida för mer information.\n\nVälkomna!",
        "timeOpen":
        {
            "monday":"08-17 (Stängt 12:30-13:30)",
            "tuesday":"08-17 (Stängt 12:30-13:30)",
            "wednesday":"08-17 (Stängt 12:30-13:30)",
            "thursday":"08-17 (Stängt 12:30-13:30)",
            "friday":"08-17 (Stängt 12:30-13:30)",
            "saturday":"8-14",
            "sunday":""
        },
        "phoneNumber":"018120065",
        "address":"Vaksalagatan 51 \n753 31, Uppsala",
        "website":"www.stahlenscykel.se",
        "email":"stahlen@gmail.com"
    },{
        "name":"Fålhagens Cykel",
        "latitude":59.859213,
        "longitude":17.656016,
        "description":"",
        "timeOpen":
        {
            "monday":"-",
            "tuesday":"-",
            "wednesday":"-",
            "thursday":"-",
            "friday":"-",
            "saturday":"-",
            "sunday":"-"
        },
        "phoneNumber":"07701950950",
        "address":"Strandbodkilen 3\n750 16, Uppsala",
        "website":"",
        "email":""
    },{
        "name":"Eriksbergs Cykel",
        "latitude":59.845591,
        "longitude":17.611771,
        "description":"Välkommen till våran verkstad.\nHär fixar vi det mesta med kort varsel. Det går även att lämna cykeln för reparation när vi har stängt. \n\nPapper, penna och plastpåse finns i en låda vid dörren, släpp sedan ner påsen med nyckeln i brevinkastet. \nFyll i lappen med mobilnummer så skickar vi ett sms när den är klar.",
        "timeOpen":
        {
            "monday":"12-18",
            "tuesday":"12-18",
            "wednesday":"12-18",
            "thursday":"12-18",
            "friday":"12-16",
            "saturday":"",
            "sunday":""
        },
        "phoneNumber":"018538770",
        "address":"Karlsrogatan 82 \n752 39, Uppsala",
        "website":"http://www.eriksbergscykel.se",
        "email":"info@eriksbergscykel.se"
    },{
        "name":"Salabacke Cykel",
        "latitude":59.87005,
        "longitude":17.67005,
        "description":"",
        "timeOpen":
        {
            "monday":"-",
            "tuesday":"-",
            "wednesday":"-",
            "thursday":"-",
            "friday":"-",
            "saturday":"-",
            "sunday":"-"
        },
        "phoneNumber":"018257302",
        "address":"Skomakargatan 14\n754 34, Uppsala",
        "website":"",
        "email":""
    },{
        "name":"Cykel Nestor's",
        "latitude":59.864912,
        "longitude":17.640520,
        "description":"",
        "timeOpen":
        {
            "monday":"10-18",
            "tuesday":"10-18",
            "wednesday":"10-18",
            "thursday":"10-18",
            "friday":"10-18",
            "saturday":"10-14",
            "sunday":""
        },
        "phoneNumber":"018107326",
        "address":"Salagatan 6\n753 30, Uppsala",
        "website":"",
        "email":""
    }];



var pump = [{
    "name":"Svandammen",
    "latitude":59.854666,
    "longitude":17.644397,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Olrogs plats",
    "latitude":59.857036,
    "longitude":17.641275,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Vaksala torg",
    "latitude":59.861174,
    "longitude":17.648656,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Polacksbacken",
    "latitude":59.840789,
    "longitude":17.648764,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Ångströmslaboratoriet, S",
    "latitude":59.837576,
    "longitude":17.647583,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Ångströmslaboratoriet, N",
    "latitude":59.839317,
    "longitude":17.648013,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Biomedicinskt centrum, Ö",
    "latitude":59.842589,
    "longitude":17.636887,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Biomedicinskt centrum, V",
    "latitude":59.842384,
    "longitude":17.632391,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Campus1477, Blåsenhus",
    "latitude":59.850056,
    "longitude":17.632257,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Norravägen",
    "latitude":59.843656,
    "longitude":17.637584,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Villavägen",
    "latitude":59.846647,
    "longitude":17.63061,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Blåsenhus, Villavägen",
    "latitude":59.84863,
    "longitude":17.629473,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Uppsala Arkivcentrum",
    "latitude":59.848738,
    "longitude":17.633979,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Blåsenhus bibliotek",
    "latitude":59.851325,
    "longitude":17.631297,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Plantskolegränd",
    "latitude":59.851222,
    "longitude":17.629119,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Humanistiskt centrum",
    "latitude":59.853367,
    "longitude":17.624141,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Thunbergsvägen",
    "latitude":59.853135,
    "longitude":17.62707,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Flogstavägen",
    "latitude":59.849538,
    "longitude":17.582481,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Sibyllegatan",
    "latitude":59.860516,
    "longitude":17.612092,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Kyrkogatan",
    "latitude":59.858599,
    "longitude":17.621641,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Geijersgatan",
    "latitude":59.863748,
    "longitude":17.621657,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Linnégatan",
    "latitude":59.861343,
    "longitude":17.634454,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"OKQ8 Kungsgatan",
    "latitude":59.847896,
    "longitude":17.664413,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Standbogatan",
    "latitude":59.854265,
    "longitude":17.650830,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Cykel-Viktor",
    "latitude":59.861402,
    "longitude":17.634009,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},
    {
        "name":"Uppsala kommun Vård och bildning",
        "latitude":59.855316,
        "longitude":17.644905,
        "description":"",
        "timeOpen":
        {
            "monday":"",
            "tuesday":"",
            "wednesday":"",
            "thursday":"",
            "friday":"",
            "saturday":"",
            "sunday":""
        },
        "phoneNumber":"",
        "address":"",
        "website":"",
        "email":""
    },
    {
        "name":"ICA Hörnan",
        "latitude":59.846066,
        "longitude":17.631171,
        "description":"",
        "timeOpen":
        {
            "monday":"",
            "tuesday":"",
            "wednesday":"",
            "thursday":"",
            "friday":"",
            "saturday":"",
            "sunday":""
        },
        "phoneNumber":"",
        "address":"",
        "website":"",
        "email":""
    },
    {
        "name":"Gränby Centrum",
        "latitude":59.877188,
        "longitude":17.674038,
        "description":"",
        "timeOpen":
        {
            "monday":"",
            "tuesday":"",
            "wednesday":"",
            "thursday":"",
            "friday":"",
            "saturday":"",
            "sunday":""
        },
        "phoneNumber":"",
        "address":"",
        "website":"",
        "email":""
    },
    {
        "name":"Akademiska Sjukhuset",
        "latitude":59.850027,
        "longitude":17.641682,
        "description":"",
        "timeOpen":
        {
            "monday":"",
            "tuesday":"",
            "wednesday":"",
            "thursday":"",
            "friday":"",
            "saturday":"",
            "sunday":""
        },
        "phoneNumber":"",
        "address":"",
        "website":"",
        "email":""
    },
    {
        "name":"Knivsta Kommunhus",
        "latitude":59.726729,
        "longitude":17.786966,
        "description":"",
        "timeOpen":
        {
            "monday":"",
            "tuesday":"",
            "wednesday":"",
            "thursday":"",
            "friday":"",
            "saturday":"",
            "sunday":""
        },
        "phoneNumber":"",
        "address":"",
        "website":"",
        "email":""
    }];




    var cykelparkering = [{
    "name":"Svandammen",
    "latitude":59.854666,
    "longitude":17.644397,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Olrogs plats",
    "latitude":59.857036,
    "longitude":17.641275,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
},{
    "name":"Vaksala torg",
    "latitude":59.861174,
    "longitude":17.648656,
    "description":"",
    "timeOpen":
    {
        "monday":"",
        "tuesday":"",
        "wednesday":"",
        "thursday":"",
        "friday":"",
        "saturday":"",
        "sunday":""
    },
    "phoneNumber":"",
    "address":"",
    "website":"",
    "email":""
}];


 var issues = [{
    "latitude":59.854655,
    "longitude":17.644370,
    "description":"",
    "issuetype":"vegetation",
    "status":"red",
    "date" :"-datum-"
},{
    "latitude":59.854661,
    "longitude":17.644389,
    "description":"",
    "issuetype":"vegetation",
    "status":"yellow",
    "date" :"-datum-"
},{
    "latitude":59.854664,
    "longitude":17.644395,
    "description":"",
    "issuetype":"vegetation",
    "status":"green",
    "date" :"-datum-"
}];